#!/usr/bin/env zsh

function getdir(){
    file_type=$2
    for element in `ls $1`
    do  
        dir_or_file=$1"/"$element
        if [ -d $dir_or_file ]
        then 
            getdir $dir_or_file $file_type
        else
            # echo $dir_or_file
            ext=${dir_or_file##*.}
            if [ $ext = $file_type ]
            then
                #使用 sed 与 cat 除去空白行
            	cat -s $dir_or_file | sed '/^[[:space:]]*$/d' >> results5.txt
        	fi
        fi  
    done
}
if [ $# = 2 ]
then
    dir=$1
    ext=$2
    getdir $dir $ext
else
	echo "请输入dir"
fi