#!/usr/bin/env zsh
# 只列出当前目录下的目录
for file in $(ls -d */)
do
 if [[ $file != "release.sh" && $file != "gl.sh" ]]
 then
    echo "The project is: --------------------- $file -----------------------------------"
    cd $file
    git checkout develop
    git pull
    cd ..
 fi
done
